[Unit]
RequiresMountsFor=
RequiresMountsFor=/data/ollama

[Service]
WorkingDirectory=/data/ollama
Environment="HOME=/data/ollama"
Environment="OLLAMA_CONTEXT_LENGTH=64000"
Environment="OLLAMA_MODELS=/data/ollama"
