################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=DP-1, 2560x1440@200, auto-right, 1, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, sdrsaturation, 0.98
monitor=DP-2, 2560x1440@200, auto-left, 1, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, sdrsaturation, 0.98
