windowrule {
    name = hide-explorer
    match:class = ^explorer.exe$

    workspace = 6 silent
}

windowrule {
    name = stick-launcher-with-steam
    match:class = ^jagexlauncher.exe$
    match:title = ^Jagex Launcher$

    workspace = 4
}
